name: Build TWRP [lake]

on:
  workflow_dispatch:

jobs:
  build:

    name: Build TWRP
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Print default env
      run: env

    - name: Build
      uses: linastorvaldz/twrp-builder-action@master
      with:
        USER_NAME: eraselk
        USER_EMAIL: eraselk@proton.me
        TWRP_SYNC_BRANCH: 12.1
        DEVICE_TREE: https://github.com/VannTakashi/recovery_xiaomi_lake
        DEVICE_TREE_BRANCH: lake.12-1
        DEVICE_PATH: device/xiaomi/lake
        DEVICE_NAME: lake
        BUILD_TARGET: vendorboot
        TG_CHAT_ID: ${{ secrets.CHAT_ID }}
        TG_TOKEN: ${{ secrets.TG_TOKEN }}
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
